test:
  failing:
    test: "exit 1"
    should_fail: true
